In [1]:
import pandas as pd
import numpy as np
import random

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [2]:
from google.colab import files
uploaded = files.upload()

Saving urldata.csv to urldata.csv


In [3]:
urls_data = pd.read_csv("urldata.csv", index_col=0)
urls_data.head()

url   label  result
0     https://www.google.com  benign       0
1    https://www.youtube.com  benign       0
2   https://www.facebook.com  benign       0
3      https://www.baidu.com  benign       0
4  https://www.wikipedia.org  benign       0

In [4]:
def makeTokens(f):
    tkns_BySlash = str(f.encode('utf-8')).split('/')	# make tokens after splitting by slash
    total_Tokens = []
    for i in tkns_BySlash:
        tokens = str(i).split('-')	# make tokens after splitting by dash
        tkns_ByDot = []
        for j in range(0,len(tokens)):
            temp_Tokens = str(tokens[j]).split('.')	# make tokens after splitting by dot
            tkns_ByDot = tkns_ByDot + temp_Tokens
        total_Tokens = total_Tokens + tokens + tkns_ByDot
    total_Tokens = list(set(total_Tokens))	#remove redundant tokens
    if 'com' in total_Tokens:
        total_Tokens.remove('com')	#removing .com since it occurs a lot of times and it should not be included in our features
    return total_Tokens

In [5]:
y = urls_data["result"]

In [6]:
y.unique()

array([0, 1])

In [7]:
url_list = urls_data["url"]

In [8]:
vectorizer = TfidfVectorizer(tokenizer=makeTokens)

In [9]:
X = vectorizer.fit_transform(url_list)

In [10]:
X.shape

(450176, 780471)

In [11]:
pip install catboost

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 76.6/76.6 MB 12.1 MB/s eta 0:00:00


In [12]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, GradientBoostingClassifier, BaggingClassifier
import xgboost as xgb
from catboost import CatBoostClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier

In [13]:
from sklearn.metrics import accuracy_score, confusion_matrix, recall_score, precision_score, f1_score

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
logit = LogisticRegression()
logit.fit(X_train, y_train)

LogisticRegression()

In [ ]:
print("Accuracy ",logit.score(X_test, y_test))

Accuracy  0.9948020791683326


In [ ]:
pred2 = logit.predict(X_test)
print(confusion_matrix(y_test, pred2))
print(accuracy_score(y_test, pred2), recall_score(y_test, pred2), precision_score(y_test, pred2),  f1_score(y_test, pred2))

[[68919     2]
 [  466 20649]]
0.9948020791683326 0.97793038124556 0.9999031523897148 0.9887947134032467


In [ ]:
pred2 = logit.predict(X_train)
print(confusion_matrix(y_train, pred2))
print(accuracy_score(y_train, pred2), recall_score(y_train, pred2), precision_score(y_train, pred2),  f1_score(y_train, pred2))

[[276813      4]
 [  1409  81914]]
0.996076525795524 0.9830899031479904 0.999951170682878 0.9914488534927771


In [ ]:
model2 = DecisionTreeClassifier()
model2.fit(X_train, y_train)

pred2 = model2.predict(X_test)
print(confusion_matrix(y_test, pred2))
print(accuracy_score(y_test, pred2), recall_score(y_test, pred2), precision_score(y_test, pred2),  f1_score(y_test, pred2))

[[68864    57]
 [  102 21013]]
0.9982340397174464 0.9951693109164101 0.9972947318462269 0.9962308877563114


In [ ]:
pr2 = model2.predict(X_train)
print(confusion_matrix(y_train, pr2))
print(accuracy_score(y_train, pr2), recall_score(y_train, pr2), precision_score(y_train, pr2),  f1_score(y_train, pr2))

[[276817      0]
 [     0  83323]]
1.0 1.0 1.0 1.0


In [ ]:
model2 = DecisionTreeClassifier()
bag_clf = BaggingClassifier(base_estimator=model2, n_estimators=100)
bag_clf.fit(X_train, y_train)

pred_bag = bag_clf.predict(X_test)
print(confusion_matrix(y_test, pred_bag))
print(accuracy_score(y_test, pred_bag), recall_score(y_test, pred_bag), precision_score(y_test, pred_bag),  f1_score(y_test, pred_bag))

In [ ]:
pr2 = bag_clf.predict(X_train)
print(confusion_matrix(y_train, pr2))
print(accuracy_score(y_train, pr2), recall_score(y_train, pr2), precision_score(y_train, pr2),  f1_score(y_train, pr2))

In [15]:
from sklearn.model_selection import GridSearchCV

In [ ]:
gscv_rf = RandomForestClassifier(n_estimators=100, n_jobs=-1)
# param_rf = {'n_estimators':[200, 400, 500, 600, 700, 800, 1000]}

# gscv_rf = GridSearchCV(rf, param_grid=param_rf, n_jobs=-1)
gscv_rf.fit(X_train, y_train)

pred_rf = gscv_rf.predict(X_test)
print(confusion_matrix(y_test, pred_rf))
print(accuracy_score(y_test, pred_rf), recall_score(y_test, pred_rf), precision_score(y_test, pred_rf),  f1_score(y_test, pred_rf))

[[68889    32]
 [  119 20996]]
0.9983228930649962 0.9943641960691452 0.9984782195168347 0.9964169612984363


In [ ]:
pr2 = gscv_rf.predict(X_train)
print(confusion_matrix(y_train, pr2))
print(accuracy_score(y_train, pr2), recall_score(y_train, pr2), precision_score(y_train, pr2),  f1_score(y_train, pr2))

[[276817      0]
 [     0  83323]]
1.0 1.0 1.0 1.0


In [ ]:
gscv_rf = RandomForestClassifier(n_estimators=50, n_jobs=-1)
# param_rf = {'n_estimators':[200, 400, 500, 600, 700, 800, 1000]}

# gscv_rf = GridSearchCV(rf, param_grid=param_rf, n_jobs=-1)
gscv_rf.fit(X_train, y_train)

pred_rf = gscv_rf.predict(X_test)
print(confusion_matrix(y_test, pred_rf))
print(accuracy_score(y_test, pred_rf), recall_score(y_test, pred_rf), precision_score(y_test, pred_rf),  f1_score(y_test, pred_rf))

[[68887    34]
 [  119 20996]]
0.9983006797281088 0.9943641960691452 0.9983832620066572 0.9963696761181635


In [ ]:
pr2 = gscv_rf.predict(X_train)
print(confusion_matrix(y_train, pr2))
print(accuracy_score(y_train, pr2), recall_score(y_train, pr2), precision_score(y_train, pr2),  f1_score(y_train, pr2))

[[276817      0]
 [     4  83319]]
0.9999888932081968 0.9999519940472619 1.0 0.9999759964474743


In [ ]:
#gscv_rf.best_params_

In [ ]:
gscv_gb = GradientBoostingClassifier(n_estimators=50, n_jobs=-1)
# param_gb = {'n_estimators':[700, 800, 900, 1000, 1100, 1200, 1300]}

# gscv_gb = GridSearchCV(gb, param_grid=param_gb, n_jobs=-1)
gscv_gb.fit(X_train, y_train)

pred_gb = gscv_gb.predict(X_test)
print(confusion_matrix(y_test, pred_gb))
print(accuracy_score(y_test, pred_gb), recall_score(y_test, pred_gb), precision_score(y_test, pred_gb),  f1_score(y_test, pred_gb))

In [ ]:
pr2 = gscv_gb.predict(X_train)
print(confusion_matrix(y_train, pr2))
print(accuracy_score(y_train, pr2), recall_score(y_train, pr2), precision_score(y_train, pr2),  f1_score(y_train, pr2))

In [ ]:
#gscv_gb.best_params_

In [ ]:
gscv_ab = AdaBoostClassifier(n_estimators=50, n_jobs=-1)
# param_ab = {'n_estimators':[700, 800, 900, 1000, 1100, 1200, 1300]}

# gscv_ab = GridSearchCV(ab, param_grid=param_ab, n_jobs=-1)
gscv_ab.fit(X_train, y_train)

pred_ab = gscv_ab.predict(X_test)
print(confusion_matrix(y_test, pred_ab))
print(accuracy_score(y_test, pred_ab), recall_score(y_test, pred_ab), precision_score(y_test, pred_ab),  f1_score(y_test, pred_ab))

In [ ]:
pr2 = gscv_ab.predict(X_train)
print(confusion_matrix(y_train, pr2))
print(accuracy_score(y_train, pr2), recall_score(y_train, pr2), precision_score(y_train, pr2),  f1_score(y_train, pr2))

In [ ]:
#gscv_ab.best_params_

In [ ]:
gscv_xb = xgb.XGBClassifier(n_estimators=500)
# param_xb = {'n_estimators':[700, 800, 900, 1000, 1100, 1200, 1300]}

# gscv_xb = GridSearchCV(xb, param_grid=param_xb, n_jobs=-1)
gscv_xb.fit(X_train, y_train)

pred_xb = gscv_xb.predict(X_test)
print(confusion_matrix(y_test, pred_xb))
print(accuracy_score(y_test, pred_xb), recall_score(y_test, pred_xb), precision_score(y_test, pred_xb),  f1_score(y_test, pred_xb))

D:\AnacondaNavigator\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[15:13:29] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[[68875    46]
 [  134 20981]]
0.998000799680128 0.9936538006156761 0.9978123365197128 0.9957287266859666


In [ ]:
pr2 = gscv_xb.predict(X_train)
print(confusion_matrix(y_train, pr2))
print(accuracy_score(y_train, pr2), recall_score(y_train, pr2), precision_score(y_train, pr2),  f1_score(y_train, pr2))

[[276710    107]
 [   355  82968]]
0.9987171655467318 0.9957394716944901 0.9987120072223894 0.9972235243212058


In [ ]:
#gscv_xb.best_params_

In [ ]:
cb = CatBoostClassifier(n_estimators=500)
cb.fit(X_train, y_train)

pred_cb = cb.predict(X_test)
print(confusion_matrix(y_test, pred_cb))
print(accuracy_score(y_test, pred_cb), recall_score(y_test, pred_cb), precision_score(y_test, pred_cb),  f1_score(y_test, pred_cb))

Learning rate set to 0.24021
0:	learn: 0.1891841	total: 4.92s	remaining: 40m 54s
1:	learn: 0.0704305	total: 8.63s	remaining: 35m 49s
2:	learn: 0.0357784	total: 11.8s	remaining: 32m 40s
3:	learn: 0.0234963	total: 15.3s	remaining: 31m 40s
4:	learn: 0.0185126	total: 18.8s	remaining: 30m 57s
5:	learn: 0.0163698	total: 22.1s	remaining: 30m 19s
6:	learn: 0.0158579	total: 25.3s	remaining: 29m 43s
7:	learn: 0.0155386	total: 28.5s	remaining: 29m 9s
8:	learn: 0.0151340	total: 31.6s	remaining: 28m 46s
9:	learn: 0.0149476	total: 34.9s	remaining: 28m 28s
10:	learn: 0.0148453	total: 38.2s	remaining: 28m 17s
11:	learn: 0.0139928	total: 41.6s	remaining: 28m 10s
12:	learn: 0.0139131	total: 44.7s	remaining: 27m 55s
13:	learn: 0.0138438	total: 47.9s	remaining: 27m 41s
14:	learn: 0.0137769	total: 51s	remaining: 27m 28s
15:	learn: 0.0137220	total: 54.1s	remaining: 27m 16s
16:	learn: 0.0136613	total: 57.2s	remaining: 27m 5s
17:	learn: 0.0136081	total: 1m	remaining: 26m 56s
18:	learn: 0.0135612	total: 1m 3s	

152:	learn: 0.0092563	total: 8m 8s	remaining: 18m 27s
153:	learn: 0.0092390	total: 8m 11s	remaining: 18m 24s
154:	learn: 0.0092268	total: 8m 14s	remaining: 18m 21s
155:	learn: 0.0092145	total: 8m 17s	remaining: 18m 17s
156:	learn: 0.0092025	total: 8m 21s	remaining: 18m 14s
157:	learn: 0.0091898	total: 8m 24s	remaining: 18m 11s
158:	learn: 0.0091744	total: 8m 27s	remaining: 18m 7s
159:	learn: 0.0091620	total: 8m 30s	remaining: 18m 4s
160:	learn: 0.0091497	total: 8m 33s	remaining: 18m 1s
161:	learn: 0.0091374	total: 8m 36s	remaining: 17m 57s
162:	learn: 0.0091253	total: 8m 39s	remaining: 17m 54s
163:	learn: 0.0091132	total: 8m 42s	remaining: 17m 50s
164:	learn: 0.0091012	total: 8m 45s	remaining: 17m 47s
165:	learn: 0.0090887	total: 8m 48s	remaining: 17m 44s
166:	learn: 0.0090765	total: 8m 52s	remaining: 17m 40s
167:	learn: 0.0090642	total: 8m 55s	remaining: 17m 37s
168:	learn: 0.0090522	total: 8m 58s	remaining: 17m 34s
169:	learn: 0.0090391	total: 9m 1s	remaining: 17m 30s
170:	learn: 0.0

300:	learn: 0.0076318	total: 15m 49s	remaining: 10m 28s
301:	learn: 0.0076241	total: 15m 53s	remaining: 10m 24s
302:	learn: 0.0076166	total: 15m 56s	remaining: 10m 21s
303:	learn: 0.0076073	total: 15m 59s	remaining: 10m 18s
304:	learn: 0.0075996	total: 16m 2s	remaining: 10m 15s
305:	learn: 0.0075921	total: 16m 5s	remaining: 10m 12s
306:	learn: 0.0075840	total: 16m 8s	remaining: 10m 8s
307:	learn: 0.0075766	total: 16m 11s	remaining: 10m 5s
308:	learn: 0.0075690	total: 16m 15s	remaining: 10m 2s
309:	learn: 0.0075602	total: 16m 18s	remaining: 9m 59s
310:	learn: 0.0074961	total: 16m 21s	remaining: 9m 56s
311:	learn: 0.0074886	total: 16m 24s	remaining: 9m 53s
312:	learn: 0.0074808	total: 16m 27s	remaining: 9m 50s
313:	learn: 0.0074733	total: 16m 30s	remaining: 9m 46s
314:	learn: 0.0074649	total: 16m 33s	remaining: 9m 43s
315:	learn: 0.0074539	total: 16m 37s	remaining: 9m 40s
316:	learn: 0.0074460	total: 16m 40s	remaining: 9m 37s
317:	learn: 0.0074376	total: 16m 43s	remaining: 9m 34s
318:	le

451:	learn: 0.0065530	total: 23m 45s	remaining: 2m 31s
452:	learn: 0.0065484	total: 23m 48s	remaining: 2m 28s
453:	learn: 0.0065431	total: 23m 51s	remaining: 2m 25s
454:	learn: 0.0065381	total: 23m 54s	remaining: 2m 21s
455:	learn: 0.0065330	total: 23m 57s	remaining: 2m 18s
456:	learn: 0.0065277	total: 24m	remaining: 2m 15s
457:	learn: 0.0065278	total: 24m 3s	remaining: 2m 12s
458:	learn: 0.0065164	total: 24m 6s	remaining: 2m 9s
459:	learn: 0.0065115	total: 24m 9s	remaining: 2m 6s
460:	learn: 0.0065070	total: 24m 12s	remaining: 2m 2s
461:	learn: 0.0065021	total: 24m 16s	remaining: 1m 59s
462:	learn: 0.0064964	total: 24m 19s	remaining: 1m 56s
463:	learn: 0.0064890	total: 24m 22s	remaining: 1m 53s
464:	learn: 0.0064833	total: 24m 25s	remaining: 1m 50s
465:	learn: 0.0064832	total: 24m 28s	remaining: 1m 47s
466:	learn: 0.0064712	total: 24m 31s	remaining: 1m 43s
467:	learn: 0.0064662	total: 24m 34s	remaining: 1m 40s
468:	learn: 0.0064613	total: 24m 37s	remaining: 1m 37s
469:	learn: 0.006453

In [ ]:
pr2 = cb.predict(X_train)
print(confusion_matrix(y_train, pr2))
print(accuracy_score(y_train, pr2), recall_score(y_train, pr2), precision_score(y_train, pr2),  f1_score(y_train, pr2))

[[276582    235]
 [   465  82858]]
0.9980563114344422 0.9944193079941913 0.9971718435969336 0.9957936736852225


In [ ]:
import math
n = (int(math.sqrt(X_train.shape[0]))//2)*2+1

In [ ]:
knn = KNeighborsClassifier(n_neighbors=n, weights='distance')
knn.fit(X_train, y_train)

pred_knn = knn.predict(X_test)
print(confusion_matrix(y_test, pred_knn))
print(accuracy_score(y_test, pred_knn), recall_score(y_test, pred_knn), precision_score(y_test, pred_knn),  f1_score(y_test, pred_knn))

[[68078   843]
 [ 2477 18638]]
0.9631258607668044 0.882690030783803 0.9567270673990041 0.9182185436988866


In [ ]:
sv = SVC()
sv.fit(X_train, y_train)

pred_sv = sv.predict(X_test)
print(confusion_matrix(y_test, pred_sv))
print(accuracy_score(y_test, pred_sv), recall_score(y_test, pred_sv), precision_score(y_test, pred_sv),  f1_score(y_test, pred_sv))

In [2]:
from sklearn.naive_bayes import MultinomialNB, GaussianNB, BernoulliNB

In [ ]:
mnb = MultinomialNB()
mnb.fit(X_train, y_train)

pred_nb = mnb.predict(X_test)
print(confusion_matrix(y_test, pred_nb))
print(accuracy_score(y_test, pred_nb), recall_score(y_test, pred_nb), precision_score(y_test, pred_nb),  f1_score(y_test, pred_nb))

[[68860    61]
 [  855 20260]]
0.98982629170554 0.9595074591522614 0.9969981792234635 0.9778936190752003


In [ ]:
bnb = BernoulliNB()
bnb.fit(X_train, y_train)

pred_nb = bnb.predict(X_test)
print(confusion_matrix(y_test, pred_nb))
print(accuracy_score(y_test, pred_nb), recall_score(y_test, pred_nb), precision_score(y_test, pred_nb),  f1_score(y_test, pred_nb))

[[68914     7]
 [  327 20788]]
0.9962903727397929 0.9845133791143736 0.9996633806203414 0.9920305416368408


In [ ]:
pred_nb = bnb.predict(X_train)
print(confusion_matrix(y_train, pred_nb))
print(accuracy_score(y_train, pred_nb), recall_score(y_train, pred_nb), precision_score(y_train, pred_nb),  f1_score(y_train, pred_nb))

[[276805     12]
 [   989  82334]]
0.9972205253512523 0.988130528185495 0.9998542734316178 0.993957831579837


In [ ]:
lr_m = [99.48]
dt_m = [99.82]
xgb_m = [99.80]
knn_m = [96.31]
cb_m = [99.75]
mnb_m = [98.98]
bnb_m = [99.63]

In [ ]:
for i in [53, 72, 96, 21]:
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=i, stratify=y)

    model = LogisticRegression()
    model.fit(X_train, y_train)

    pred = model.predict(X_test)
    print("LR:")
    print(confusion_matrix(y_test, pred))
    print(accuracy_score(y_test, pred), recall_score(y_test, pred), precision_score(y_test, pred),  f1_score(y_test, pred))
    lr_m.append(accuracy_score(y_test, pred))

    
    model2 = DecisionTreeClassifier()
    model2.fit(X_train, y_train)

    pred2 = model2.predict(X_test)
    print("DTC:")
    print(confusion_matrix(y_test, pred2))
    print(accuracy_score(y_test, pred2), recall_score(y_test, pred2), precision_score(y_test, pred2),  f1_score(y_test, pred2))
    dt_m.append(accuracy_score(y_test, pred2))


    xb = xgb.XGBClassifier(n_estimators=700)
    xb.fit(X_train, y_train)

    pred_xb = xb.predict(X_test)
    print("XGB:")
    print(confusion_matrix(y_test, pred_xb))
    print(accuracy_score(y_test, pred_xb), recall_score(y_test, pred_xb), precision_score(y_test, pred_xb),  f1_score(y_test, pred_xb))
    xgb_m.append(accuracy_score(y_test, pred_xb))


    n = (int(math.sqrt(X_train.shape[0]))//2)*2+1

    knn = KNeighborsClassifier(n_neighbors=n, weights='distance')
    knn.fit(X_train, y_train)

    pred_knn = knn.predict(X_test)
    print("KNN:")
    print(confusion_matrix(y_test, pred_knn))
    print(accuracy_score(y_test, pred_knn), recall_score(y_test, pred_knn), precision_score(y_test, pred_knn),  f1_score(y_test, pred_knn))
    knn_m.append(accuracy_score(y_test, pred_knn))


    cb = CatBoostClassifier(n_estimators=500)
    cb.fit(X_train, y_train)

    pred_cb = cb.predict(X_test)
    print("CB:")
    print(confusion_matrix(y_test, pred_cb))
    print(accuracy_score(y_test, pred_cb), recall_score(y_test, pred_cb), precision_score(y_test, pred_cb),  f1_score(y_test, pred_cb))
    cb_m.append(accuracy_score(y_test, pred_cb))
    
    
    mnb = MultinomialNB()
    mnb.fit(X_train, y_train)

    pred_nb = mnb.predict(X_test)
    print("MNB:")
    print(confusion_matrix(y_test, pred_nb))
    print(accuracy_score(y_test, pred_nb), recall_score(y_test, pred_nb), precision_score(y_test, pred_nb),  f1_score(y_test, pred_nb))
    mnb_m.append(accuracy_score(y_test, pred_nb))
    
    
    bnb = BernoulliNB()
    bnb.fit(X_train, y_train)

    pred_nb = bnb.predict(X_test)
    print("BNB:")
    print(confusion_matrix(y_test, pred_nb))
    print(accuracy_score(y_test, pred_nb), recall_score(y_test, pred_nb), precision_score(y_test, pred_nb),  f1_score(y_test, pred_nb))
    bnb_m.append(accuracy_score(y_test, pred_nb))

D:\AnacondaNavigator\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LR:
[[69147     1]
 [  435 20453]]
0.9951574925585321 0.9791746457296056 0.9999511098073727 0.9894538241981521
DTC:
[[69082    66]
 [  101 20787]]
0.9981451863698965 0.9951646878590579 0.9968349877715437 0.9959991375386311


D:\AnacondaNavigator\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[12:42:43] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
XGB:
[[69093    55]
 [  124 20764]]
0.9980119063485717 0.9940635771734967 0.9973581824295115 0.9957081545064377
KNN:
[[68336   812]
 [ 2449 18439]]
0.9637811542049847 0.8827556491765607 0.957820372967638 0.918757318318842
Learning rate set to 0.24021
0:	learn: 0.1903641	total: 1.98s	remaining: 16m 26s
1:	learn: 0.0713218	total: 3.83s	remaining: 15m 52s
2:	learn: 0.0364528	total: 5.84s	remaining: 16m 7s
3:	learn: 0.0237670	total: 7.77s	remaining: 16m 3s
4:	learn: 0.0186260	total: 9.66s	remaining: 15m 56s
5:	learn: 0.0167432	total: 11.4s	remaining: 15m 37s
6:	learn: 0.0158345	total: 13.2s	remaining: 15m 27s
7:	learn: 0.0155136	total: 14.8s	remaining: 15m 13s
8:	learn: 0.0152237	total

143:	learn: 0.0091970	total: 3m 47s	remaining: 9m 21s
144:	learn: 0.0091844	total: 3m 48s	remaining: 9m 20s
145:	learn: 0.0091717	total: 3m 50s	remaining: 9m 18s
146:	learn: 0.0091591	total: 3m 51s	remaining: 9m 16s
147:	learn: 0.0091464	total: 3m 53s	remaining: 9m 15s
148:	learn: 0.0091338	total: 3m 54s	remaining: 9m 13s
149:	learn: 0.0091213	total: 3m 56s	remaining: 9m 11s
150:	learn: 0.0091085	total: 3m 57s	remaining: 9m 9s
151:	learn: 0.0090959	total: 3m 59s	remaining: 9m 8s
152:	learn: 0.0090837	total: 4m	remaining: 9m 6s
153:	learn: 0.0090710	total: 4m 2s	remaining: 9m 4s
154:	learn: 0.0090589	total: 4m 4s	remaining: 9m 3s
155:	learn: 0.0090463	total: 4m 5s	remaining: 9m 1s
156:	learn: 0.0090339	total: 4m 7s	remaining: 8m 59s
157:	learn: 0.0090216	total: 4m 8s	remaining: 8m 58s
158:	learn: 0.0090091	total: 4m 10s	remaining: 8m 56s
159:	learn: 0.0089961	total: 4m 11s	remaining: 8m 54s
160:	learn: 0.0089837	total: 4m 13s	remaining: 8m 53s
161:	learn: 0.0089713	total: 4m 14s	remaini

296:	learn: 0.0074906	total: 7m 42s	remaining: 5m 15s
297:	learn: 0.0074825	total: 7m 43s	remaining: 5m 14s
298:	learn: 0.0074741	total: 7m 45s	remaining: 5m 12s
299:	learn: 0.0074642	total: 7m 46s	remaining: 5m 11s
300:	learn: 0.0074559	total: 7m 48s	remaining: 5m 9s
301:	learn: 0.0074479	total: 7m 49s	remaining: 5m 8s
302:	learn: 0.0074404	total: 7m 51s	remaining: 5m 6s
303:	learn: 0.0074312	total: 7m 52s	remaining: 5m 4s
304:	learn: 0.0074235	total: 7m 54s	remaining: 5m 3s
305:	learn: 0.0074161	total: 7m 55s	remaining: 5m 1s
306:	learn: 0.0074064	total: 7m 57s	remaining: 5m
307:	learn: 0.0073985	total: 7m 58s	remaining: 4m 58s
308:	learn: 0.0073911	total: 8m	remaining: 4m 56s
309:	learn: 0.0073833	total: 8m 1s	remaining: 4m 55s
310:	learn: 0.0073739	total: 8m 3s	remaining: 4m 53s
311:	learn: 0.0073643	total: 8m 5s	remaining: 4m 52s
312:	learn: 0.0073571	total: 8m 6s	remaining: 4m 50s
313:	learn: 0.0073499	total: 8m 8s	remaining: 4m 49s
314:	learn: 0.0073408	total: 8m 9s	remaining: 4

448:	learn: 0.0062674	total: 11m 35s	remaining: 1m 18s
449:	learn: 0.0062574	total: 11m 36s	remaining: 1m 17s
450:	learn: 0.0062574	total: 11m 38s	remaining: 1m 15s
451:	learn: 0.0062536	total: 11m 39s	remaining: 1m 14s
452:	learn: 0.0062481	total: 11m 41s	remaining: 1m 12s
453:	learn: 0.0062437	total: 11m 42s	remaining: 1m 11s
454:	learn: 0.0062393	total: 11m 44s	remaining: 1m 9s
455:	learn: 0.0062347	total: 11m 46s	remaining: 1m 8s
456:	learn: 0.0062346	total: 11m 47s	remaining: 1m 6s
457:	learn: 0.0062243	total: 11m 49s	remaining: 1m 5s
458:	learn: 0.0062195	total: 11m 50s	remaining: 1m 3s
459:	learn: 0.0062155	total: 11m 52s	remaining: 1m 1s
460:	learn: 0.0062154	total: 11m 53s	remaining: 1m
461:	learn: 0.0062067	total: 11m 55s	remaining: 58.8s
462:	learn: 0.0061989	total: 11m 56s	remaining: 57.3s
463:	learn: 0.0061946	total: 11m 58s	remaining: 55.7s
464:	learn: 0.0061856	total: 11m 59s	remaining: 54.2s
465:	learn: 0.0061805	total: 12m 1s	remaining: 52.6s
466:	learn: 0.0061766	tota

D:\AnacondaNavigator\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[13:26:05] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
XGB:
[[69092    56]
 [  142 20746]]
0.9978008796481408 0.9932018383761011 0.9973079511585424 0.9952506596306068
KNN:
[[68300   848]
 [ 2573 18315]]
0.9620040872539873 0.8768192263500575 0.9557480561498721 0.9145839055204613
Learning rate set to 0.24021
0:	learn: 0.1898387	total: 2.19s	remaining: 18m 13s
1:	learn: 0.0711128	total: 4.21s	remaining: 17m 29s
2:	learn: 0.0368643	total: 6.32s	remaining: 17m 26s
3:	learn: 0.0239893	total: 8.37s	remaining: 17m 17s
4:	learn: 0.0188687	total: 10.4s	remaining: 17m 10s
5:	learn: 0.0171343	total: 12.3s	remaining: 16m 51s
6:	learn: 0.0166331	total: 14.2s	remaining: 16m 43s
7:	learn: 0.0163401	total: 16s	remaining: 16m 26s
8:	learn: 0.0152292	tot

143:	learn: 0.0092397	total: 4m 18s	remaining: 10m 38s
144:	learn: 0.0092272	total: 4m 20s	remaining: 10m 36s
145:	learn: 0.0092146	total: 4m 21s	remaining: 10m 35s
146:	learn: 0.0092019	total: 4m 23s	remaining: 10m 33s
147:	learn: 0.0091894	total: 4m 25s	remaining: 10m 31s
148:	learn: 0.0091770	total: 4m 27s	remaining: 10m 29s
149:	learn: 0.0091645	total: 4m 29s	remaining: 10m 27s
150:	learn: 0.0091519	total: 4m 30s	remaining: 10m 25s
151:	learn: 0.0091396	total: 4m 32s	remaining: 10m 23s
152:	learn: 0.0091271	total: 4m 34s	remaining: 10m 22s
153:	learn: 0.0091148	total: 4m 36s	remaining: 10m 20s
154:	learn: 0.0091022	total: 4m 37s	remaining: 10m 18s
155:	learn: 0.0090899	total: 4m 39s	remaining: 10m 16s
156:	learn: 0.0090773	total: 4m 41s	remaining: 10m 14s
157:	learn: 0.0090650	total: 4m 43s	remaining: 10m 12s
158:	learn: 0.0090526	total: 4m 44s	remaining: 10m 10s
159:	learn: 0.0090403	total: 4m 46s	remaining: 10m 8s
160:	learn: 0.0090279	total: 4m 48s	remaining: 10m 7s
161:	learn: 

296:	learn: 0.0075824	total: 8m 47s	remaining: 6m
297:	learn: 0.0075741	total: 8m 49s	remaining: 5m 58s
298:	learn: 0.0075666	total: 8m 51s	remaining: 5m 57s
299:	learn: 0.0075588	total: 8m 52s	remaining: 5m 55s
300:	learn: 0.0075511	total: 8m 54s	remaining: 5m 53s
301:	learn: 0.0075431	total: 8m 56s	remaining: 5m 51s
302:	learn: 0.0075325	total: 8m 58s	remaining: 5m 49s
303:	learn: 0.0075251	total: 8m 59s	remaining: 5m 48s
304:	learn: 0.0075164	total: 9m 1s	remaining: 5m 46s
305:	learn: 0.0075083	total: 9m 3s	remaining: 5m 44s
306:	learn: 0.0075009	total: 9m 5s	remaining: 5m 42s
307:	learn: 0.0074927	total: 9m 6s	remaining: 5m 40s
308:	learn: 0.0074849	total: 9m 8s	remaining: 5m 39s
309:	learn: 0.0074765	total: 9m 10s	remaining: 5m 37s
310:	learn: 0.0074684	total: 9m 12s	remaining: 5m 35s
311:	learn: 0.0074604	total: 9m 13s	remaining: 5m 33s
312:	learn: 0.0074531	total: 9m 15s	remaining: 5m 31s
313:	learn: 0.0074455	total: 9m 17s	remaining: 5m 30s
314:	learn: 0.0074378	total: 9m 19s	r

447:	learn: 0.0064134	total: 13m 13s	remaining: 1m 32s
448:	learn: 0.0064090	total: 13m 15s	remaining: 1m 30s
449:	learn: 0.0064046	total: 13m 16s	remaining: 1m 28s
450:	learn: 0.0064002	total: 13m 18s	remaining: 1m 26s
451:	learn: 0.0063954	total: 13m 20s	remaining: 1m 24s
452:	learn: 0.0063875	total: 13m 22s	remaining: 1m 23s
453:	learn: 0.0063826	total: 13m 23s	remaining: 1m 21s
454:	learn: 0.0063780	total: 13m 25s	remaining: 1m 19s
455:	learn: 0.0063737	total: 13m 27s	remaining: 1m 17s
456:	learn: 0.0063686	total: 13m 29s	remaining: 1m 16s
457:	learn: 0.0063664	total: 13m 30s	remaining: 1m 14s
458:	learn: 0.0063617	total: 13m 32s	remaining: 1m 12s
459:	learn: 0.0063379	total: 13m 34s	remaining: 1m 10s
460:	learn: 0.0063334	total: 13m 36s	remaining: 1m 9s
461:	learn: 0.0062945	total: 13m 38s	remaining: 1m 7s
462:	learn: 0.0062886	total: 13m 39s	remaining: 1m 5s
463:	learn: 0.0062885	total: 13m 41s	remaining: 1m 3s
464:	learn: 0.0062828	total: 13m 43s	remaining: 1m 1s
465:	learn: 0.0

D:\AnacondaNavigator\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[14:12:27] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
XGB:
[[69096    52]
 [  135 20753]]
0.9979230530010218 0.9935369590195328 0.9975006008171112 0.9955148346245173
KNN:
[[68302   846]
 [ 2531 18357]]
0.9624927806655116 0.8788299502106472 0.9559443836900484 0.915766630914669
Learning rate set to 0.24021
0:	learn: 0.1903493	total: 1.98s	remaining: 16m 26s
1:	learn: 0.0714433	total: 3.63s	remaining: 15m 3s
2:	learn: 0.0353125	total: 5.41s	remaining: 14m 56s
3:	learn: 0.0237120	total: 7.09s	remaining: 14m 39s
4:	learn: 0.0188793	total: 8.8s	remaining: 14m 31s
5:	learn: 0.0170858	total: 10.3s	remaining: 14m 10s
6:	learn: 0.0164151	total: 11.9s	remaining: 13m 56s
7:	learn: 0.0160934	total: 13.4s	remaining: 13m 43s
8:	learn: 0.0158854	tota

143:	learn: 0.0094245	total: 3m 48s	remaining: 9m 24s
144:	learn: 0.0094107	total: 3m 49s	remaining: 9m 22s
145:	learn: 0.0093981	total: 3m 51s	remaining: 9m 21s
146:	learn: 0.0093857	total: 3m 53s	remaining: 9m 19s
147:	learn: 0.0093730	total: 3m 54s	remaining: 9m 17s
148:	learn: 0.0093604	total: 3m 56s	remaining: 9m 16s
149:	learn: 0.0093479	total: 3m 57s	remaining: 9m 14s
150:	learn: 0.0093314	total: 3m 59s	remaining: 9m 12s
151:	learn: 0.0093189	total: 4m	remaining: 9m 11s
152:	learn: 0.0093064	total: 4m 2s	remaining: 9m 9s
153:	learn: 0.0092942	total: 4m 3s	remaining: 9m 7s
154:	learn: 0.0092817	total: 4m 5s	remaining: 9m 6s
155:	learn: 0.0092693	total: 4m 6s	remaining: 9m 4s
156:	learn: 0.0092567	total: 4m 8s	remaining: 9m 2s
157:	learn: 0.0092443	total: 4m 9s	remaining: 9m 1s
158:	learn: 0.0092318	total: 4m 11s	remaining: 8m 59s
159:	learn: 0.0092195	total: 4m 13s	remaining: 8m 57s
160:	learn: 0.0092075	total: 4m 14s	remaining: 8m 56s
161:	learn: 0.0091950	total: 4m 16s	remainin

297:	learn: 0.0075395	total: 7m 45s	remaining: 5m 15s
298:	learn: 0.0075315	total: 7m 47s	remaining: 5m 14s
299:	learn: 0.0075233	total: 7m 48s	remaining: 5m 12s
300:	learn: 0.0075153	total: 7m 50s	remaining: 5m 10s
301:	learn: 0.0075069	total: 7m 51s	remaining: 5m 9s
302:	learn: 0.0074988	total: 7m 53s	remaining: 5m 7s
303:	learn: 0.0074898	total: 7m 54s	remaining: 5m 6s
304:	learn: 0.0074824	total: 7m 56s	remaining: 5m 4s
305:	learn: 0.0074739	total: 7m 57s	remaining: 5m 3s
306:	learn: 0.0074661	total: 7m 59s	remaining: 5m 1s
307:	learn: 0.0074553	total: 8m 1s	remaining: 4m 59s
308:	learn: 0.0074476	total: 8m 2s	remaining: 4m 58s
309:	learn: 0.0074398	total: 8m 4s	remaining: 4m 56s
310:	learn: 0.0074322	total: 8m 5s	remaining: 4m 55s
311:	learn: 0.0074240	total: 8m 7s	remaining: 4m 53s
312:	learn: 0.0074130	total: 8m 8s	remaining: 4m 51s
313:	learn: 0.0074055	total: 8m 10s	remaining: 4m 50s
314:	learn: 0.0073692	total: 8m 11s	remaining: 4m 48s
315:	learn: 0.0073617	total: 8m 13s	rema

449:	learn: 0.0063827	total: 11m 40s	remaining: 1m 17s
450:	learn: 0.0063748	total: 11m 41s	remaining: 1m 16s
451:	learn: 0.0062686	total: 11m 43s	remaining: 1m 14s
452:	learn: 0.0062624	total: 11m 45s	remaining: 1m 13s
453:	learn: 0.0062537	total: 11m 46s	remaining: 1m 11s
454:	learn: 0.0062491	total: 11m 48s	remaining: 1m 10s
455:	learn: 0.0062433	total: 11m 49s	remaining: 1m 8s
456:	learn: 0.0062381	total: 11m 51s	remaining: 1m 6s
457:	learn: 0.0062338	total: 11m 52s	remaining: 1m 5s
458:	learn: 0.0062287	total: 11m 54s	remaining: 1m 3s
459:	learn: 0.0062241	total: 11m 55s	remaining: 1m 2s
460:	learn: 0.0062184	total: 11m 57s	remaining: 1m
461:	learn: 0.0062127	total: 11m 59s	remaining: 59.1s
462:	learn: 0.0062057	total: 12m	remaining: 57.6s
463:	learn: 0.0062009	total: 12m 2s	remaining: 56s
464:	learn: 0.0062009	total: 12m 3s	remaining: 54.5s
465:	learn: 0.0061856	total: 12m 5s	remaining: 52.9s
466:	learn: 0.0061855	total: 12m 6s	remaining: 51.4s
467:	learn: 0.0061738	total: 12m 8s

D:\AnacondaNavigator\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[14:57:37] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
XGB:
[[69101    47]
 [  140 20748]]
0.9979230530010218 0.9932975871313673 0.9977398413080067 0.9955137586066262
KNN:
[[68322   826]
 [ 2539 18349]]
0.9626260606868364 0.8784469551895825 0.9569230769230769 0.91600728852058
Learning rate set to 0.24021
0:	learn: 0.1896242	total: 1.69s	remaining: 14m
1:	learn: 0.0774764	total: 3.5s	remaining: 14m 31s
2:	learn: 0.0388843	total: 5.39s	remaining: 14m 52s
3:	learn: 0.0250968	total: 7.18s	remaining: 14m 50s
4:	learn: 0.0192416	total: 9.7s	remaining: 16m
5:	learn: 0.0168434	total: 11.4s	remaining: 15m 39s
6:	learn: 0.0160206	total: 12.9s	remaining: 15m 11s
7:	learn: 0.0156258	total: 14.5s	remaining: 14m 51s
8:	learn: 0.0153869	total: 16s	re

144:	learn: 0.0091806	total: 3m 47s	remaining: 9m 17s
145:	learn: 0.0091675	total: 3m 49s	remaining: 9m 15s
146:	learn: 0.0091515	total: 3m 50s	remaining: 9m 14s
147:	learn: 0.0091392	total: 3m 52s	remaining: 9m 12s
148:	learn: 0.0091263	total: 3m 53s	remaining: 9m 10s
149:	learn: 0.0091133	total: 3m 55s	remaining: 9m 9s
150:	learn: 0.0091018	total: 3m 56s	remaining: 9m 7s
151:	learn: 0.0090887	total: 3m 58s	remaining: 9m 5s
152:	learn: 0.0090768	total: 3m 59s	remaining: 9m 4s
153:	learn: 0.0090637	total: 4m 1s	remaining: 9m 2s
154:	learn: 0.0090521	total: 4m 3s	remaining: 9m
155:	learn: 0.0090399	total: 4m 4s	remaining: 8m 59s
156:	learn: 0.0090267	total: 4m 6s	remaining: 8m 57s
157:	learn: 0.0090142	total: 4m 7s	remaining: 8m 55s
158:	learn: 0.0090021	total: 4m 9s	remaining: 8m 54s
159:	learn: 0.0089906	total: 4m 10s	remaining: 8m 52s
160:	learn: 0.0089776	total: 4m 12s	remaining: 8m 51s
161:	learn: 0.0089663	total: 4m 13s	remaining: 8m 49s
162:	learn: 0.0089533	total: 4m 15s	remaini

297:	learn: 0.0075074	total: 7m 43s	remaining: 5m 14s
298:	learn: 0.0074995	total: 7m 45s	remaining: 5m 12s
299:	learn: 0.0074909	total: 7m 46s	remaining: 5m 11s
300:	learn: 0.0074832	total: 7m 48s	remaining: 5m 9s
301:	learn: 0.0074749	total: 7m 49s	remaining: 5m 7s
302:	learn: 0.0074673	total: 7m 51s	remaining: 5m 6s
303:	learn: 0.0074604	total: 7m 52s	remaining: 5m 4s
304:	learn: 0.0074519	total: 7m 54s	remaining: 5m 3s
305:	learn: 0.0074438	total: 7m 55s	remaining: 5m 1s
306:	learn: 0.0074363	total: 7m 57s	remaining: 4m 59s
307:	learn: 0.0074289	total: 7m 58s	remaining: 4m 58s
308:	learn: 0.0074205	total: 8m	remaining: 4m 57s
309:	learn: 0.0074110	total: 8m 2s	remaining: 4m 55s
310:	learn: 0.0074045	total: 8m 3s	remaining: 4m 53s
311:	learn: 0.0073968	total: 8m 5s	remaining: 4m 52s
312:	learn: 0.0073885	total: 8m 6s	remaining: 4m 50s
313:	learn: 0.0073824	total: 8m 8s	remaining: 4m 49s
314:	learn: 0.0073744	total: 8m 9s	remaining: 4m 47s
315:	learn: 0.0073659	total: 8m 11s	remainin

449:	learn: 0.0062661	total: 11m 36s	remaining: 1m 17s
450:	learn: 0.0062617	total: 11m 37s	remaining: 1m 15s
451:	learn: 0.0062548	total: 11m 39s	remaining: 1m 14s
452:	learn: 0.0062476	total: 11m 40s	remaining: 1m 12s
453:	learn: 0.0062422	total: 11m 42s	remaining: 1m 11s
454:	learn: 0.0062352	total: 11m 43s	remaining: 1m 9s
455:	learn: 0.0062346	total: 11m 45s	remaining: 1m 8s
456:	learn: 0.0062274	total: 11m 46s	remaining: 1m 6s
457:	learn: 0.0062198	total: 11m 48s	remaining: 1m 4s
458:	learn: 0.0062156	total: 11m 49s	remaining: 1m 3s
459:	learn: 0.0062101	total: 11m 51s	remaining: 1m 1s
460:	learn: 0.0062051	total: 11m 53s	remaining: 1m
461:	learn: 0.0061995	total: 11m 54s	remaining: 58.8s
462:	learn: 0.0061934	total: 11m 56s	remaining: 57.2s
463:	learn: 0.0061881	total: 11m 57s	remaining: 55.7s
464:	learn: 0.0061711	total: 11m 59s	remaining: 54.1s
465:	learn: 0.0061633	total: 12m	remaining: 52.6s
466:	learn: 0.0061595	total: 12m 2s	remaining: 51s
467:	learn: 0.0061544	total: 12m 

In [ ]:
for model in [lr_m, dt_m, xgb_m, cb_m, knn_m, mnb_m, bnb_m]:
    print(np.mean(model), np.std(model))

99.478 0.019390719429666442
99.818 0.007483314773545635
99.792 0.007483314773545634
99.76599999999999 0.010198039027184655
96.28 0.060991802727905275
98.95 0.029664793948382496
99.636 0.012000000000002349


In [2]:
rf_m = [99.83]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=53, stratify=y)

gscv_rf = RandomForestClassifier(n_estimators=50, n_jobs=-1)
gscv_rf.fit(X_train, y_train)

pred_rf = gscv_rf.predict(X_test)
rf_m.append(accuracy_score(y_test, pred_rf))
print(confusion_matrix(y_test, pred_rf))
print(accuracy_score(y_test, pred_rf), recall_score(y_test, pred_rf), precision_score(y_test, pred_rf),  f1_score(y_test, pred_rf))

[[69114    34]
 [  118 20770]]
0.9983117863965525 0.9943508234392953 0.9983656989040569 0.9963542166362851


In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=72, stratify=y)

gscv_rf = RandomForestClassifier(n_estimators=50, n_jobs=-1)
gscv_rf.fit(X_train, y_train)

pred_rf = gscv_rf.predict(X_test)
rf_m.append(accuracy_score(y_test, pred_rf))
print(confusion_matrix(y_test, pred_rf))
print(accuracy_score(y_test, pred_rf), recall_score(y_test, pred_rf), precision_score(y_test, pred_rf),  f1_score(y_test, pred_rf))

[[69119    29]
 [  149 20739]]
0.9980230130170155 0.9928667177326694 0.9986036209553159 0.9957269060879584


In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=96, stratify=y)

gscv_rf = RandomForestClassifier(n_estimators=50, n_jobs=-1)
gscv_rf.fit(X_train, y_train)

pred_rf = gscv_rf.predict(X_test)
rf_m.append(accuracy_score(y_test, pred_rf))
print(confusion_matrix(y_test, pred_rf))
print(accuracy_score(y_test, pred_rf), recall_score(y_test, pred_rf), precision_score(y_test, pred_rf),  f1_score(y_test, pred_rf))

[[69107    41]
 [   99 20789]]
0.9984450664178773 0.9952604366143241 0.9980316850696112 0.9966441344263868


In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=21, stratify=y)

gscv_rf = RandomForestClassifier(n_estimators=50, n_jobs=-1)
gscv_rf.fit(X_train, y_train)

pred_rf = gscv_rf.predict(X_test)
rf_m.append(accuracy_score(y_test, pred_rf))
print(confusion_matrix(y_test, pred_rf))
print(accuracy_score(y_test, pred_rf), recall_score(y_test, pred_rf), precision_score(y_test, pred_rf),  f1_score(y_test, pred_rf))

[[69096    52]
 [   99 20789]]
0.9983228930649962 0.9952604366143241 0.997504918190106 0.9963814134055452


In [3]:
rf_m[-1] = 99.83
print(rf_m)

[99.83, 99.83, 99.8, 99.84, 99.83]
